<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZTxpI9N\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZTxpI9N/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerZTxpI9N.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerZTxpI9N\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerZTxpI9N\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'ZTxpI9N',
    'container.build_id' => 'fd5ac7bd',
    'container.build_time' => 1565006687,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZTxpI9N');
