<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDiatCG8\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDiatCG8/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDiatCG8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDiatCG8\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerDiatCG8\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'DiatCG8',
    'container.build_id' => '6c321b60',
    'container.build_time' => 1565023797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDiatCG8');
