<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8stIT1D\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8stIT1D/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8stIT1D.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8stIT1D\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container8stIT1D\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '8stIT1D',
    'container.build_id' => '60fa8d93',
    'container.build_time' => 1565006139,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8stIT1D');
